# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  external_labels:
    monitor: 'kb-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - 157.245.240.248:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - 'prometheus.rules.yml'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.

scrape_configs:
# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['157.245.240.248:9090']

  - job_name: 'cloudwatch'
    scrape_interval: 5s
    static_configs:
    - targets: ['157.245.240.248:9106']

  - job_name: 'node'
    static_configs:
    - targets: ['3.14.10.65:9100']
      labels:
        group: 'was'
    - targets: ['3.133.119.42:9100']
      labels:
        group: 'db'
    - targets: ['18.216.28.112:9100']
      labels:
        group: 'web'
    - targets: ['13.59.166.108:9100']
      labels:
        group: 'common'
