---
region: us-east-2
metrics:

- aws_namespace: AWS/EC2
  aws_metric_name: CPUUtilization
  aws_dimensions: [InstanceId, InstanceType, ImageId]
  aws_statistics: [Average]

- aws_namespace: AWS/EC2
  aws_metric_name: StatusCheckFailed
  aws_dimensions: [InstanceId, InstanceType, ImageId]
  aws_statistics: [Average]
